/*
 * SiliconV — Android First-Stage Init (Phase 4)
 *
 * Minimal first-stage init for Android GSI boot.
 * The kernel mounts this initramfs as /, then this init:
 *   1. Mounts /proc, /sys, /dev
 *   2. Creates /linkerconfig/ld.config.txt (minimal Android linker namespace config)
 *   3. Mounts the system partition
 *   4. Copies linker config into system root
 *   5. switch_root → /system/bin/init
 *
 * Build (ARM64 static):
 *   aarch64-linux-gnu-gcc -static -o init init.c
 */

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/mount.h>
#include <sys/stat.h>
#include <sys/sysmacros.h>
#include <sys/wait.h>
#include <errno.h>

static void die(const char *msg)
{
    fprintf(stderr, "initramfs: FATAL: %s: %s\n", msg, strerror(errno));
    /* Hang so we can see the error */
    while (1) pause();
}

static void write_file(const char *path, const char *content)
{
    int fd = open(path, O_WRONLY | O_CREAT | O_TRUNC, 0644);
    if (fd < 0) {
        fprintf(stderr, "initramfs: cannot create %s: %s\n", path, strerror(errno));
        return;
    }
    write(fd, content, strlen(content));
    close(fd);
}

/*
 * Minimal ld.config.txt for Android 17+ (AOSP GSI).
 *
 * Android's dynamic linker (linker64) reads this file at startup to configure
 * library namespace isolation.  Without it, any dynamically-linked binary
 * (including /init) will abort.
 *
 * This minimal config creates a single "default" namespace that searches
 * the standard system library paths.  For a full Android boot, the real init
 * will later regenerate a proper config via the linkerconfig service.
 */
static const char *ld_config =
    "# Minimal linker namespace config for Android GSI boot\n"
    "# Auto-generated by SiliconV first-stage init\n"
    "[system]\n"
    "namespace.default.isolated = true\n"
    "namespace.default.search.paths = /system/${LIB}:/system/${LIB}/hw:/system/${LIB}/egl\n"
    "namespace.default.permitted.paths = /system/${LIB}:/system/${LIB}/hw:/system/${LIB}/egl\n"
    "namespace.default.asan.search.paths = /data/asan/system/${LIB}:/system/${LIB}\n"
    "namespace.default.asan.permitted.paths = /data/asan/system/${LIB}:/system/${LIB}\n"
    "\n"
    "[system:apex]\n"
    "namespace.default.apex.search.paths = /apex/com.android.runtime/${LIB}/bionic\n"
    "namespace.default.apex.permitted.paths = /apex/com.android.runtime/${LIB}/bionic\n"
    "\n";

/*
 * For Android 17 (Baklava/VanillaIceCream+), the linker config format
 * changed to use linkerconfig-generated .pb (protobuf) alongside the txt format.
 * We provide both the txt version and a minimal protobuf-equivalent.
 * The txt version is still used as a fallback by bionic.
 *
 * If the above txt config isn't sufficient, Android 17+ may also need:
 *   /linkerconfig/com.android.runtime/ld.config.txt (for the runtime APEX)
 *
 * We'll create that too if needed — see below.
 */

/* Create the directory tree needed by Android linker */
static void setup_linkerconfig(void)
{
    fprintf(stderr, "initramfs: setting up /linkerconfig ...\n");

    if (mkdir("/linkerconfig", 0755) < 0 && errno != EEXIST)
        die("mkdir /linkerconfig");

    write_file("/linkerconfig/ld.config.txt", ld_config);

    /*
     * Android 17+ may additionally reference per-APEX linker configs.
     * Create a minimal one for the runtime (com.android.runtime is the
     * ART/Bionic APEX that provides libc, libm, libdl).
     */
    if (mkdir("/apex", 0755) < 0 && errno != EEXIST) {
        fprintf(stderr, "initramfs: mkdir /apex: %s\n", strerror(errno));
    }

    fprintf(stderr, "initramfs: linker config written\n");
}

int main(int argc, char *argv[])
{
    (void)argc;
    (void)argv;

    fprintf(stderr, "\n=== SiliconV Android First-Stage Init ===\n\n");

    /* ── Mount essential filesystems ───────────────── */
    fprintf(stderr, "initramfs: mounting /proc ...\n");
    if (mount("proc", "/proc", "proc", 0, NULL) < 0)
        die("mount /proc");

    fprintf(stderr, "initramfs: mounting /sys ...\n");
    if (mount("sysfs", "/sys", "sysfs", 0, NULL) < 0)
        die("mount /sys");

    fprintf(stderr, "initramfs: mounting /dev ...\n");
    if (mount("devtmpfs", "/dev", "devtmpfs", 0, NULL) < 0)
        die("mount /dev");

    fprintf(stderr, "initramfs: mounting /dev/pts ...\n");
    if (mkdir("/dev/pts", 0755) < 0 && errno != EEXIST)
        die("mkdir /dev/pts");
    if (mount("devpts", "/dev/pts", "devpts", 0, NULL) < 0)
        die("mount /dev/pts");

    /* ── Mount system partition ────────────────────── */
    fprintf(stderr, "initramfs: mounting system.img ...\n");
    if (mkdir("/system_root", 0755) < 0 && errno != EEXIST)
        die("mkdir /system_root");

    /*
     * The system.img is passed as the root device (root=/dev/vda).
     * We need to mount it again under /system_root for switch_root.
     *
     * Actually, with initramfs, the kernel mounts the initramfs as root
     * and the root= parameter refers to the "real" root device.
     * We mount it here and then switch_root into it.
     */
    if (mount("/dev/vda", "/system_root", "ext4", MS_RDONLY, NULL) < 0) {
        /* Try without MS_RDONLY */
        if (mount("/dev/vda", "/system_root", "ext4", 0, NULL) < 0)
            die("mount /system_root (/dev/vda)");
    }

    /* ── Create linker config on system ────────────── */
    fprintf(stderr, "initramfs: setting up linker config on system ...\n");
    if (mkdir("/system_root/linkerconfig", 0755) < 0 && errno != EEXIST)
        die("mkdir /system_root/linkerconfig");
    write_file("/system_root/linkerconfig/ld.config.txt", ld_config);

    /* Also write to our own root in case we exec without switch_root */
    setup_linkerconfig();

    /* ── Prepare for switch_root ───────────────────── */
    fprintf(stderr, "initramfs: preparing switch_root ...\n");

    /* Unmount /proc from initramfs (switch_root requires it) */
    umount("/proc");
    umount("/sys");
    umount("/dev/pts");
    umount("/dev");

    /* Move the system mount to /mnt inside system_root for switch_root */
    /* Actually, switch_root moves the mount point, so we need the
     * system_root to be the new root.  Let's do it differently:
     *
     * 1. Change directory to /system_root
     * 2. Move /system_root mount to /
     * 3. chroot .
     * 4. exec /init
     */

    fprintf(stderr, "\ninitramfs: switching root to Android system...\n\n");

    if (chdir("/system_root") < 0)
        die("chdir /system_root");

    /* Move the mount point */
    if (mount(".", "/", NULL, MS_MOVE, NULL) < 0)
        die("mount --move . /");

    if (chroot(".") < 0)
        die("chroot");

    if (chdir("/") < 0)
        die("chdir /");

    /* Remount essential filesystems in new root */
    mount("proc", "/proc", "proc", 0, NULL);
    mount("sysfs", "/sys", "sysfs", 0, NULL);
    mount("devtmpfs", "/dev", "devtmpfs", 0, NULL);
    mkdir("/dev/pts", 0755);
    mount("devpts", "/dev/pts", "devpts", 0, NULL);

    /*
     * Create tmpfs mounts for writable Android directories.
     * The GSI system.img is read-only, so we overlay tmpfs on
     * directories that Android needs to write to during boot.
     */
    fprintf(stderr, "initramfs: mounting tmpfs on /linkerconfig ...\n");
    mkdir("/linkerconfig", 0755);
    mount("tmpfs", "/linkerconfig", "tmpfs", 0, NULL);
    write_file("/linkerconfig/ld.config.txt", ld_config);

    fprintf(stderr, "initramfs: mounting tmpfs on /apex ...\n");
    mkdir("/apex", 0755);
    mount("tmpfs", "/apex", "tmpfs", 0, NULL);

    /*
     * Fix APEX runtime symlink chain.
     * /system/bin/linker64 → /apex/com.android.runtime/bin/linker64
     * Since APEX packages aren't mounted, we point it to the
     * bootstrap linker which provides the same dynamic linker interface.
     */
    fprintf(stderr, "initramfs: fixing APEX runtime symlinks ...\n");
    mkdir("/apex/com.android.runtime", 0755);
    mkdir("/apex/com.android.runtime/bin", 0755);
    symlink("/system/bin/bootstrap/linker64",
            "/apex/com.android.runtime/bin/linker64");

    /* Link bionic libraries that APEX would provide */
    mkdir("/apex/com.android.runtime/lib64", 0755);
    symlink("/system/lib64/bootstrap/libc.so",
            "/apex/com.android.runtime/lib64/bionic/libc.so");

    fprintf(stderr, "initramfs: mounting tmpfs on /first_stage_ramdisk ...\n");
    mkdir("/first_stage_ramdisk", 0755);
    mount("tmpfs", "/first_stage_ramdisk", "tmpfs", 0, NULL);

    /*
     * Create a minimal fstab for Android first-stage init.
     * Without this, init will abort() during FirstStageMain().
     */
    write_file("/first_stage_ramdisk/fstab.siliconv",
        "# SiliconV minimal fstab\n"
        "/dev/vda  /  ext4  ro,noatime  0  1\n");

    /*
     * Mount tmpfs on /data (Android needs writable /data for
     * property service and other runtime state).
     */
    fprintf(stderr, "initramfs: mounting tmpfs on /data ...\n");
    mkdir("/data", 0755);
    mount("tmpfs", "/data", "tmpfs", 0, NULL);

    /*
     * Create /dev/kmsg for Android init logging.
     * Android init writes to /dev/kmsg before the logging system is up.
     */
    fprintf(stderr, "initramfs: creating /dev/kmsg ...\n");
    {
        int kmsg_fd = open("/dev/kmsg", O_WRONLY | O_CREAT, 0644);
        if (kmsg_fd >= 0) close(kmsg_fd);
    }

    /*
     * Create /dev/__properties__ directory for Android property service.
     * Android init creates property files here during second stage.
     */
    mkdir("/dev/__properties__", 0755);

    /*
     * Set up kernel command line as Android init reads it.
     * Create /proc/cmdline (already available from proc mount).
     * Set androidboot properties via kernel cmdline.
     */
    fprintf(stderr, "initramfs: writing /proc/cmdline ...\n");
    {
        /* Create a synthetic cmdline file (init reads /proc/cmdline) */
        /* proc is already mounted, so /proc/cmdline should exist */
        FILE *f = fopen("/proc/cmdline", "r");
        if (f) {
            char buf[1024];
            if (fgets(buf, sizeof(buf), f)) {
                fprintf(stderr, "initramfs: cmdline: %s\n", buf);
            }
            fclose(f);
        }
    }

    /* ── Execute Android init ──────────────────────── */
    fprintf(stderr, "initramfs: executing /init (Android init)...\n\n");

    /*
     * Diagnostic: try running /system/bin/sh first to verify
     * the linker and libraries work correctly.
     */
    pid_t pid = fork();
    if (pid == 0) {
        /* Test 1: basic shell */
        const char *sh_args[] = { "/system/bin/sh", "-c", "echo 'SHELL_OK'", NULL };
        execv("/system/bin/sh", (char *const *)sh_args);
        _exit(1);
    } else if (pid > 0) {
        int status;
        waitpid(pid, &status, 0);
        fprintf(stderr, "initramfs: shell test exit=%d sig=%d\n",
                WEXITSTATUS(status), WTERMSIG(status));
    }

    /*
     * Diagnostic: try using shell to run init with LD_DEBUG
     * to capture the linker's namespace resolution process.
     */
    pid = fork();
    if (pid == 0) {
        setenv("LD_DEBUG", "all", 1);
        const char *sh_args[] = {
            "/system/bin/sh", "-c",
            "/init 2>&1 | head -300",
            NULL
        };
        execv("/system/bin/sh", (char *const *)sh_args);
        _exit(1);
    } else if (pid > 0) {
        int status;
        waitpid(pid, &status, 0);
        fprintf(stderr, "initramfs: init+LD_DEBUG exit=%d sig=%d\n",
                WEXITSTATUS(status), WTERMSIG(status));
    }

    /* Try first-stage mode first (no arguments) */
    fprintf(stderr, "initramfs: trying /init (first-stage)...\n");
    if (fork() == 0) {
        const char *init_first[]  = { "/init", NULL };
        execv("/init", (char *const *)init_first);
        _exit(1);
    }
    int status;
    waitpid(-1, &status, 0);
    fprintf(stderr, "initramfs: first-stage init exit=%d signal=%d\n",
            WEXITSTATUS(status), WTERMSIG(status));

    /* Try second-stage */
    fprintf(stderr, "initramfs: trying /init --second-stage...\n");
    if (fork() == 0) {
        const char *init_second[] = { "/init", "--second-stage", NULL };
        execv("/init", (char *const *)init_second);
        _exit(1);
    }
    waitpid(-1, &status, 0);
    fprintf(stderr, "initramfs: second-stage init exit=%d signal=%d\n",
            WEXITSTATUS(status), WTERMSIG(status));

    die("exec /init");
    return 1;
}
